gipsydangermessage:
    resource: "@gipsydangermessageBundle/Resources/config/routing.yml"
    prefix:   /

gipsydangersearch:
    resource: "@gipsydangersearchBundle/Resources/config/routing.yml"
    prefix:   /

gipsydangerpeople:
    resource: "@gipsydangerpeopleBundle/Resources/config/routing.yml"
    prefix:   /profile/

gipsydangerindex:
    resource: "@gipsydangerindexBundle/Resources/config/routing.yml"
    prefix:   /

