gipsydangerpeople_profile:
    pattern:  /profile/{username}
    defaults: { _controller: gipsydangerpeopleBundle:profile:show }

gipsydangerpeople_login:
    pattern:  /login/
    defaults: { _controller: gipsydangerpeopleBundle:accounts:login }

gipsydangerpeople_signup:
    pattern:  /sign-up/
    defaults: { _controller: gipsydangerpeopleBundle:accounts:signup }

gipsydangerpeople_signup_coach:
    pattern: /sign-up/coach/
    defaults: {_controller: gipsydangerpeopleBundle:accounts:signupForm, type: coach}

gipsydangerpeople_signup_user:
    pattern: /sign-up/normal/
    defaults: {_controller: gipsydangerpeopleBundle:accounts:signupForm, type: normal}

gipsydangerpeople_signup_complete:
    pattern: /sign-up/complete/
    defaults: { _controller: gipsydangerpeopleBundle:accounts:completeRegistration }
