parameters:
#    gipsydangerpeople.example.class: gipsydanger\peopleBundle\Example

services:
#    gipsydangerpeople.example:
#        class: %gipsydangerpeople.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
