parameters:
#    gipsydangermessage.example.class: gipsydanger\messageBundle\Example

services:
#    gipsydangermessage.example:
#        class: %gipsydangermessage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
